"""create a auth,contact, account tables 

Revision ID: 0397b5fdbf7c
Revises: 208272896677
Create Date: 2026-02-19 05:32:29.213056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0397b5fdbf7c'
down_revision: Union[str, Sequence[str], None] = '208272896677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('billing_street', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('shipping_street', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=100), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lead_source', sa.String(length=50), nullable=True),
    sa.Column('account_score', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('annual_revenue >= 0', name='ck_account_revenue_positive'),
    sa.CheckConstraint('employees >= 0', name='ck_account_employees_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_active', 'accounts', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_account_name_search', 'accounts', ['account_name'], unique=False, postgresql_using='gin', postgresql_ops={'account_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=False)
    op.create_index(op.f('ix_accounts_account_score'), 'accounts', ['account_score'], unique=False)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_created_by'), 'accounts', ['created_by'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_industry'), 'accounts', ['industry'], unique=False)
    op.create_index(op.f('ix_accounts_lead_source'), 'accounts', ['lead_source'], unique=False)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index('uq_account_tenant_name', 'accounts', ['tenant_id', 'account_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('auth_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('password_algo', sa.String(length=20), nullable=True),
    sa.Column('is_password_set', sa.Boolean(), nullable=False),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_provider IN ('LOCAL', 'GOOGLE', 'AZURE', 'OKTA', 'GITHUB', 'SAML', 'OAUTH')", name='ck_auth_provider_valid'),
    sa.CheckConstraint("password_algo IN ('bcrypt', 'argon2id') OR password_algo IS NULL", name='ck_password_algo_valid'),
    sa.CheckConstraint('(is_password_set = true AND password_hash IS NOT NULL AND password_algo IS NOT NULL) OR (is_password_set = false AND password_hash IS NULL AND password_algo IS NULL)', name='ck_password_consistency'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_credentials_auth_provider'), 'auth_credentials', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_auth_credentials_user_id'), 'auth_credentials', ['user_id'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('home_phone', sa.String(length=20), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('mailing_street', sa.String(length=255), nullable=True),
    sa.Column('mailing_city', sa.String(length=100), nullable=True),
    sa.Column('mailing_state', sa.String(length=100), nullable=True),
    sa.Column('mailing_zip', sa.String(length=20), nullable=True),
    sa.Column('mailing_country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lead_source', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('last_activity_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_full_name_search', 'contacts', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_created_by'), 'contacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_contacts_date_of_birth'), 'contacts', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_email_opt_out'), 'contacts', ['email_opt_out'], unique=False)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_full_name'), 'contacts', ['full_name'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contacts_last_activity_time'), 'contacts', ['last_activity_time'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_index(op.f('ix_contacts_lead_source'), 'contacts', ['lead_source'], unique=False)
    op.create_index(op.f('ix_contacts_next_follow_up_date'), 'contacts', ['next_follow_up_date'], unique=False)
    op.create_index(op.f('ix_contacts_owner_id'), 'contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_contacts_status'), 'contacts', ['status'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_index('uq_contact_tenant_email', 'contacts', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_foreign_key('fk_users_role_id', 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_users_profile_id', 'users', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    op.drop_constraint('fk_users_profile_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_role_id', 'users', type_='foreignkey')
    op.drop_index('uq_contact_tenant_email', table_name='contacts', postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_next_follow_up_date'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lead_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_activity_time'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_full_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email_opt_out'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_date_of_birth'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_by'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.drop_index('ix_contact_full_name_search', table_name='contacts', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('contacts')
    op.drop_index(op.f('ix_auth_credentials_user_id'), table_name='auth_credentials')
    op.drop_index(op.f('ix_auth_credentials_auth_provider'), table_name='auth_credentials')
    op.drop_table('auth_credentials')
    op.drop_index('uq_account_tenant_name', table_name='accounts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_lead_source'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_industry'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_by'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_score'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.drop_index('ix_account_name_search', table_name='accounts', postgresql_using='gin', postgresql_ops={'account_name': 'gin_trgm_ops'})
    op.drop_index('ix_account_active', table_name='accounts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('accounts')
    # ### end Alembic commands ###
