"""create a pipeline_stage tables 

Revision ID: 0a15db9b6c2e
Revises: eed374ad92ee
Create Date: 2026-02-20 10:22:33.038597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a15db9b6c2e'
down_revision: Union[str, Sequence[str], None] = 'eed374ad92ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('is_won_stage', sa.Boolean(), nullable=False),
    sa.Column('is_lost_stage', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('order_index IS NULL OR order_index>= 0', name='ck_pipeline_stage_display_order_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'name', name='uq_pipeline_stage_name_per_pipeline')
    )
    op.create_index('ix_pipeline_stage_active', 'pipeline_stages', ['pipeline_id', 'name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_pipeline_stages_created_at'), 'pipeline_stages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_created_by'), 'pipeline_stages', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_id'), 'pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_name'), 'pipeline_stages', ['name'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_name'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_created_by'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_created_at'), table_name='pipeline_stages')
    op.drop_index('ix_pipeline_stage_active', table_name='pipeline_stages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('pipeline_stages')
    # ### end Alembic commands ###
