"""create a pipeline_record tables 

Revision ID: e4cbf292e367
Revises: 0a15db9b6c2e
Create Date: 2026-02-27 06:33:30.908131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4cbf292e367'
down_revision: Union[str, Sequence[str], None] = '0a15db9b6c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_records_account_id'), 'pipeline_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_contact_id'), 'pipeline_records', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_created_at'), 'pipeline_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_records_created_by'), 'pipeline_records', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_records_id'), 'pipeline_records', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_owner_id'), 'pipeline_records', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_pipeline_id'), 'pipeline_records', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_stage_id'), 'pipeline_records', ['stage_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_status'), 'pipeline_records', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_records_tenant_id'), 'pipeline_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pipeline_records_title'), 'pipeline_records', ['title'], unique=False)
    op.create_index(op.f('ix_pipeline_records_value'), 'pipeline_records', ['value'], unique=False)
    op.add_column('pipelines', sa.Column('record_label', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_pipelines_record_label'), 'pipelines', ['record_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelines_record_label'), table_name='pipelines')
    op.drop_column('pipelines', 'record_label')
    op.drop_index(op.f('ix_pipeline_records_value'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_title'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_tenant_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_status'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_stage_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_pipeline_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_owner_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_created_by'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_created_at'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_contact_id'), table_name='pipeline_records')
    op.drop_index(op.f('ix_pipeline_records_account_id'), table_name='pipeline_records')
    op.drop_table('pipeline_records')
    # ### end Alembic commands ###
